spring:
  application:
    name: batch
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_service
    username: vgnc
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

